version: '3'

services:
  hackyeah-ml:
    image: pexoacr.azurecr.io/hackyeah-ml:latest
    ports:
      - "7001:106"
    volumes:
      - C:\Users\pexoy\Desktop\HackYeah\Model:/model
    networks:
      - hackyeah-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16G'

  hackyeah-api:
    image: pexoacr.azurecr.io/hackyeah-api:latest
    ports:
      - "5012:80"
    environment:
      - __MLAPIUrl__=hackyeah-ml:106
    networks:
      - hackyeah-network

  hackyeah-ui:
    image: pexoacr.azurecr.io/hackyeah-ui:latest
    ports:
      - "4200:80"
    networks:
      - hackyeah-network

networks:
  hackyeah-network:
    driver: bridge